-- Core curated knowledge seed for IQS-Framework AI Chatbot.
-- Apply after docs/ai-chatbot-knowledge-tables-2026-06-12.sql.
-- These entries are intentionally general and safe for all authenticated users.
-- Role-specific details must still come from runtime visible menu context.

INSERT INTO `tbl_ai_chat_knowledge` (
  `f_publicID`,
  `f_title`,
  `f_question`,
  `f_answer`,
  `f_language`,
  `f_visibility`,
  `f_allowedGroups`,
  `f_tags`,
  `f_status`,
  `f_priority`,
  `f_createdBy`,
  `f_createdDt`,
  `f_updatedBy`,
  `f_updatedDt`
) VALUES
(
  '11111111-1111-4111-8111-111111111111',
  'Login dan akses sistem',
  'Apa perlu dibuat jika saya tidak boleh login?',
  'Semak dahulu ID pengguna dan kata laluan yang dimasukkan. Jika akaun dikunci, kata laluan tamat tempoh, atau login masih gagal selepas beberapa cubaan, gunakan aliran reset kata laluan jika tersedia atau hubungi pentadbir sistem. AI Chatbot tidak boleh melihat, meminta, atau menukar kata laluan pengguna.',
  'ms',
  'all_authenticated',
  NULL,
  'login,akses,kata laluan,akaun',
  'active',
  10,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '22222222-2222-4222-8222-222222222222',
  'Dashboard pengguna',
  'Apa fungsi dashboard?',
  'Dashboard memaparkan ringkasan maklumat dan pintasan yang berkaitan dengan peranan aktif pengguna. Kandungan dashboard boleh berbeza mengikut kumpulan akses. Jika sesuatu kad, graf, atau pautan tidak kelihatan, kemungkinan ia tidak tersedia untuk peranan aktif semasa.',
  'ms',
  'all_authenticated',
  NULL,
  'dashboard,ringkasan,peranan aktif',
  'active',
  20,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '33333333-3333-4333-8333-333333333333',
  'Navigasi menu',
  'Bagaimana saya cari menu dalam sistem?',
  'Gunakan sidebar untuk membuka modul dan submenu yang tersedia kepada peranan aktif anda. AI Chatbot hanya boleh merujuk menu yang kelihatan dalam konteks akses semasa. Jika menu tidak muncul, semak peranan aktif di bahagian profil atau hubungi pentadbir akses.',
  'ms',
  'all_authenticated',
  NULL,
  'menu,sidebar,navigasi,modul',
  'active',
  30,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '44444444-4444-4444-8444-444444444444',
  'Peranan aktif dan akses',
  'Kenapa paparan saya berbeza daripada pengguna lain?',
  'Paparan sistem bergantung kepada peranan aktif dan kumpulan akses pengguna. Pengguna yang mempunyai lebih daripada satu peranan boleh menukar peranan aktif jika fungsi itu tersedia. Perubahan peranan boleh mengubah menu, tindakan, dan data yang boleh dilihat.',
  'ms',
  'all_authenticated',
  NULL,
  'role,peranan,kumpulan akses,akses',
  'active',
  40,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '55555555-5555-4555-8555-555555555555',
  'Manual pengguna',
  'Di mana saya boleh rujuk manual sistem?',
  'Jika modul manual tersedia untuk peranan aktif anda, buka menu manual atau panduan pengguna daripada sidebar. Manual biasanya disediakan mengikut kumpulan pengguna. Jika manual tidak tersedia atau fail tidak boleh dibuka, hubungi pentadbir sistem untuk semakan akses atau muat naik manual.',
  'ms',
  'all_authenticated',
  NULL,
  'manual,panduan pengguna,dokumen bantuan',
  'active',
  50,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '66666666-6666-4666-8666-666666666666',
  'Notifikasi sistem',
  'Bagaimana notifikasi sistem berfungsi?',
  'Notifikasi digunakan untuk memaklumkan pengguna tentang peringatan, status proses, hebahan, atau tindakan yang perlu dibuat. Senarai notifikasi bergantung kepada sasaran penerima dan peranan pengguna. Jika notifikasi penting tidak diterima, semak tetapan modul berkaitan atau hubungi pentadbir.',
  'ms',
  'all_authenticated',
  NULL,
  'notifikasi,peringatan,hebahan,tindakan',
  'active',
  60,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '77777777-7777-4777-8777-777777777777',
  'Template emel',
  'Apa kegunaan template emel?',
  'Template emel membantu sistem menghantar mesej yang konsisten untuk proses seperti reset kata laluan, makluman, dan notifikasi. Pentadbir yang mempunyai akses boleh mengurus kandungan template, placeholder, dan ujian penghantaran. Jangan simpan kata laluan, token, atau rahsia sistem dalam template.',
  'ms',
  'all_authenticated',
  NULL,
  'emel,email template,placeholder,mail',
  'active',
  70,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '88888888-8888-4888-8888-888888888888',
  'Page generator',
  'Apa fungsi page generator?',
  'Page generator membantu pentadbir atau pembangun menjana struktur halaman berdasarkan template yang disediakan oleh framework. Gunakan fungsi ini hanya jika anda mempunyai akses dan memahami kesan kepada fail aplikasi. Semak output sebelum digunakan dalam persekitaran production.',
  'ms',
  'all_authenticated',
  NULL,
  'page generator,template,developer,halaman',
  'active',
  80,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  '99999999-9999-4999-8999-999999999999',
  'Tetapan sistem',
  'Siapa boleh ubah tetapan sistem?',
  'Tetapan sistem hanya boleh diubah oleh pengguna yang mempunyai akses pentadbiran yang sesuai. Tetapan boleh melibatkan konfigurasi umum, bahasa, emel, polisi login, database, tema, dan AI Chatbot. Jika anda tidak nampak menu tetapan, peranan aktif anda mungkin tidak mempunyai kebenaran.',
  'ms',
  'all_authenticated',
  NULL,
  'tetapan sistem,konfigurasi,admin,settings',
  'active',
  90,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
),
(
  'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
  'Tetapan AI Chatbot',
  'Bagaimana AI Chatbot dikawal?',
  'AI Chatbot dikawal melalui Tetapan Sistem > AI Chatbot oleh pentadbir yang dibenarkan. Tetapan utama termasuk status aktif, provider, model, limit penggunaan, karakter, storage, dan access mode. Chatbot direka sebagai pembantu read-only dan tidak boleh menjalankan tindakan sistem atau menukar data pengguna.',
  'ms',
  'all_authenticated',
  NULL,
  'ai chatbot,tetapan chatbot,provider,model,read only',
  'active',
  100,
  'core-seed',
  NOW(),
  'core-seed',
  NOW()
)
ON DUPLICATE KEY UPDATE
  `f_title` = VALUES(`f_title`),
  `f_question` = VALUES(`f_question`),
  `f_answer` = VALUES(`f_answer`),
  `f_language` = VALUES(`f_language`),
  `f_visibility` = VALUES(`f_visibility`),
  `f_allowedGroups` = VALUES(`f_allowedGroups`),
  `f_tags` = VALUES(`f_tags`),
  `f_status` = VALUES(`f_status`),
  `f_priority` = VALUES(`f_priority`),
  `f_updatedBy` = VALUES(`f_updatedBy`),
  `f_updatedDt` = NOW();
